= Spring Batch Redis
:linkattrs:
:project-owner:   redis-developer
:project-name:    spring-batch-redis
:project-group:   com.redis
:project-version: 2.26.1

image:https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions/workflows/early-access.yml"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}[Download, link="https://search.maven.org/#search|ga|1|{project-name}"]
image:https://img.shields.io/nexus/s/{project-group}/{project-name}?server=https%3A%2F%2Fs01.oss.sonatype.org[Snapshot,link="https://s01.oss.sonatype.org/#nexus-search;quick~{project-name}"]
image:https://codecov.io/gh/{project-owner}/{project-name}/branch/master/graph/badge.svg["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]

ItemReader and ItemWriter implementations for Redis based on https://lettuce.io[Lettuce].

== Getting Started

=== Maven
Add Spring Batch Redis dependency to your POM file:

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>{project-group}</groupId>
    <artifactId>{project-name}</artifactId>
    <version>{project-version}</version>
</dependency>
----

=== Gradle
Add Spring Batch Redis dependency to your `build.gradle` file

[source,groovy]
[subs="attributes"]
.build.gradle
----
dependencies {
    implementation '{project-group}:{project-name}:{project-version}'
}
----

== Data Types
Spring Batch Redis supports two data types: key dumps (bytes) and key values (data structure-specific objects).

=== Key Dumps
A key dump object stores a key, its TTL in milliseconds, and its binary representation (byte array).

=== Data Structures
A `DataStructure` object stores a key, its TTL in seconds, the type of data structure (hash, list, ...), and its Java representation.

* Hash: `HGETALL` -> `Map<String,String>`
* List: `LRANGE` -> `List<String>`
* Set: `SMEMBERS` -> `Set<String>`
* Stream: `XRANGE` -> `List<StreamMessage<String, String>>`
* String: `GET` -> `String`
* Sorted Set: `ZRANGE` -> `List<ScoredValue<String>>`

NOTE: `StreamMessage` and `ScoredValue` are Lettuce core types (`io.lettuce.core` package).

== Item Readers

`RedisItemReader` exposes 2 operation modes:

* Snapshot: relies on SCAN command to iterate over the keys whose values will be read to produce key/values.
* Live (AKA continuous): listens to changes in the keyspace via notifications and produces corresponding key/values.

== Item Writers

`RedisItemWriter`s can perform both inserts or deletes depending on the value and TTL in the incoming object. 
If value is null or TTL is -2 then the `DEL` command is called, otherwise a write is performed.

Item writers support two different data types:

=== Key Dump

In this mode, `RedisItemWriter` accepts key dumps (`KeyValue<String, byte[]>`) and calls the RESTORE command with the byte array and TTL if any.

=== `DataStructureItemWriter`

In this mode, `RedisItemWriter` accepts `DataStructure` objects and calls the write command specific to the data type:

* Hash -> HSET
* List -> LPUSH
* Set -> SADD
* Stream -> XADD
* String -> SET
* Sorted Set -> ZADD

If TTL >= 0 then an additional call is made to `EXPIRE` command.

== Usage

Refer to https://github.com/redis-developer/spring-batch-redis/tree/master/subprojects/spring-batch-redis/src/test/java/com/redis/spring/batch[unit tests] for usage examples
