= Spring Batch Redis
// Settings
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/spring-batch-redis
:repo-url: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ItemReader and ItemWriter implementations for Redis based on https://lettuce.io[Lettuce].

== Data Types
Spring Batch Redis supports two data types: key dumps and key values.

=== `KeyDump`
A `KeyDump` stores a key, its TTL in seconds, and its binary representation (byte array).

=== `DataStructure`
A `KeyValue` stores a key, its TTL in seconds, the type of data structure (hash, list, ...), and its Java representation.

* Hash: `HGETALL` -> `Map<String,String>`
* List: `LRANGE` -> `List<String>`
* Set: `SMEMBERS` -> `Set<String>`
* Stream: `XRANGE` -> `List<StreamMessage<String, String>>`
* String: `GET` -> `String`
* Sorted Set: `ZRANGE` -> `List<ScoredValue<String>>`

NOTE: `StreamMessage` and `ScoredValue` are Lettuce core types (`io.lettuce.core` package).

== Item Readers

Each data type has 2 corresponding item readers:

* Snapshot: uses SCAN command to produce keys.
* Live (AKA continuous): uses keyspace notifications to produce keys that have been updated.

== Item Writers

All item writers can perform both inserts or deletes depending on the value and TTL in the incoming object:

* If value is null or TTL is -2 then the `DEL` command is called
* Otherwise a write is performed

=== `KeyDumpItemWriter`

`KeyDumpItemWriter` accepts `KeyDump` objects and call the RESTORE command using the byte array and TTL if any.

=== `DataStructureItemWriter`

`DataStructureItemWriter` accepts `DataStructure` objects and calls the write command specific to the data type:

* Hash -> HSET
* List -> LPUSH
* Set -> SADD
* Stream -> XADD
* String -> SET
* Sorted Set -> ZADD

If TTL >= 0 then an additional call is made to `EXPIRE` command.

== Usage

[source,java]
----
RedisClient source = RedisClient.create("redis://source:6379");
KeyDumpItemReader reader = KeyDumpItemReader.builder().client(source).build();
RedisClient target = RedisClient.create("rediss://target:6379");
KeyDumpItemWriter writer = KeyDumpItemWriter.builder().client(target).build();
TaskletStep step = stepBuilderFactory.get("step").<KeyDump, KeyDump>chunk(50).reader(reader).writer(writer).build();
jobBuilderFactory.get("job").start(step).build();
----
