= Spring Batch Redis
:linkattrs:
:project-owner:   redis-developer
:project-name:    spring-batch-redis
:project-group:   com.redislabs
:project-version: 2.13.11

image:https://github.com/{project-owner}/{project-name}/actions/workflows/gradle.yml/badge.svg["Build Status", link="https://github.com/{project-owner}/{project-name}/actions"]
image:https://codecov.io/gh/{project-owner}/{project-name}/branch/master/graph/badge.svg["Coverage", link="https://codecov.io/gh/{project-owner}/{project-name}"]
image:https://img.shields.io/maven-central/v/{project-group}/{project-name}.svg[Download, link="https://search.maven.org/#search|ga|1|{project-name}"]
image:https://img.shields.io/github/downloads/{project-owner}/{project-name}/total[GitHub all releases]

---

ItemReader and ItemWriter implementations for Redis based on https://lettuce.io[Lettuce].

== Getting Started

=== Maven
Add Spring Batch Redis dependency to your POM file:

[source,xml]
[subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>{project-group}</groupId>
    <artifactId>{project-name}</artifactId>
    <version>{project-version}</version>
</dependency>
----

=== Gradle
Add Spring Batch Redis dependency to your `build.gradle` file

[source,groovy]
[subs="attributes"]
.build.gradle
----
dependencies {
    implementation '{project-group}:{project-name}:{project-version}'
}
----

== Data Types
Spring Batch Redis supports two data types: key dumps (bytes) and key values (data structure-specific objects).

=== Key Dumps
A key dump object stores a key, its TTL in milliseconds, and its binary representation (byte array).

=== Data Structures
A `DataStructure` object stores a key, its TTL in seconds, the type of data structure (hash, list, ...), and its Java representation.

* Hash: `HGETALL` -> `Map<String,String>`
* List: `LRANGE` -> `List<String>`
* Set: `SMEMBERS` -> `Set<String>`
* Stream: `XRANGE` -> `List<StreamMessage<String, String>>`
* String: `GET` -> `String`
* Sorted Set: `ZRANGE` -> `List<ScoredValue<String>>`

NOTE: `StreamMessage` and `ScoredValue` are Lettuce core types (`io.lettuce.core` package).

== Item Readers

Each data type has 2 corresponding item readers:

* Snapshot: uses SCAN command to produce keys.
* Live (AKA continuous): uses keyspace notifications to produce keys that have been updated.

== Item Writers

All item writers can perform both inserts or deletes depending on the value and TTL in the incoming object:

* If value is null or TTL is -2 then the `DEL` command is called
* Otherwise a write is performed

=== `KeyDumpItemWriter`

`RestoreOperation` accepts `KeyDump` objects and call the RESTORE command using the byte array and TTL if any.

=== `DataStructureItemWriter`

`DataStructureItemWriter` accepts `DataStructure` objects and calls the write command specific to the data type:

* Hash -> HSET
* List -> LPUSH
* Set -> SADD
* Stream -> XADD
* String -> SET
* Sorted Set -> ZADD

If TTL >= 0 then an additional call is made to `EXPIRE` command.

== Usage

Refer to unit test for usage examples
