= Spring Batch Redis
// Settings
:idprefix:
:idseparator: -
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::env-github[:icons: font]
// URIs
:project-repo: Redislabs-Solution-Architects/spring-batch-redis
:repo-url: https://github.com/{project-repo}
// GitHub customization
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ItemReader and ItemWriter implementations for Redis based on https://lettuce.io[Lettuce].

== Data Types
Spring Batch Redis supports two data types: key dumps and key values.

=== `KeyDump`
A `KeyDump` stores a key, its TTL in seconds, and its binary representation (byte array).

=== `KeyValue`
A `KeyValue` stores a key, its TTL in seconds, the type of data structure (hash, list, ...), and its Java representation.

* Hash: `HGETALL` -> `Map<String,String>`
* List: `LRANGE` -> `List<String>`
* Set: `SMEMBERS` -> `Set<String>`
* Stream: `XRANGE` -> `List<StreamMessage<String, String>>`
* String: `GET` -> `String`
* Sorted Set: `ZRANGE` -> `List<ScoredValue<String>>`

NOTE: `StreamMessage` and `ScoredValue` are Lettuce core types (`io.lettuce.core` package).

== Item Readers

Each data type has an item reader that can operate in 2 modes:

* Snapshot: uses SCAN command to produce keys.
* Live (AKA continuous): also relies on SCAN but in addition uses keyspace notifications to keep producing keys that have been updated.

== Item Writers

All item writers can perform both inserts or deletes depending on the value and TTL in the incoming object:

* If value is null or TTL is -2 then the `DEL` command is called
* Otherwise a write is performed

=== Key Dump Writers

Key dump writers accept `KeyDump` objects and call the RESTORE command using the byte array and TTL if any.

=== Key Value Writers

Key value writers accept `KeyValue` objects and call the write command specific to the data type:

* Hash -> HMSET
* List -> LPUSH
* Set -> SADD
* Stream -> XADD
* String -> SET
* Sorted Set -> ZADD

If TTL >= 0 then an additional call is made to `EXPIRE` command.

== Usage

[source,java]
----
ReaderOptions options = ReaderOptions.builder().live(true).threadCount(2).build();
RedisKeyDumpItemReader reader = RedisKeyDumpItemReader.builder().redisURI(redisURI).options(options).build();
RedisKeyDumpItemWriter writer = RedisKeyDumpItemWriter.builder().redisURI(targetRedisURI).replace(true).build();
TaskletStep step = step.get("step").<KeyDump, KeyDump>chunk(50).reader(reader).writer(writer).build();
jobFactory.get("job").start(step).build();
----
