= Spring Batch Redis
ifdef::env-github[]
:badges:
:tag: master
:!toc-title:
endif::[]

// Badges
ifdef::badges[]
image:https://img.shields.io/github/license/redis-developer/spring-batch-redis.svg["License", link="https://github.com/redis-developer/spring-batch-redis"]
image:https://img.shields.io/github/release/redis-developer/spring-batch-redis.svg["Latest", link="https://github.com/redis-developer/spring-batch-redis/releases/latest"]
image:https://github.com/redis-developer/spring-batch-redis/actions/workflows/gradle.yml/badge.svg["Build", link="https://github.com/redis-developer/spring-batch-redis/actions/workflows/gradle.yml"]
image:https://codecov.io/gh/redis-developer/spring-batch-redis/branch/master/graph/badge.svg?token=A5IX98M8JT["Coverage", link="https://codecov.io/gh/redis-developer/spring-batch-redis"]
endif::[]


ItemReader and ItemWriter implementations for Redis based on https://lettuce.io[Lettuce].

== Data Types
Spring Batch Redis supports two data types: key dumps and key values.

=== `KeyDump`
A `KeyDump` object stores a key, its TTL in milliseconds, and its binary representation (byte array).

=== `DataStructure`
A `DataStructure` object stores a key, its TTL in seconds, the type of data structure (hash, list, ...), and its Java representation.

* Hash: `HGETALL` -> `Map<String,String>`
* List: `LRANGE` -> `List<String>`
* Set: `SMEMBERS` -> `Set<String>`
* Stream: `XRANGE` -> `List<StreamMessage<String, String>>`
* String: `GET` -> `String`
* Sorted Set: `ZRANGE` -> `List<ScoredValue<String>>`

NOTE: `StreamMessage` and `ScoredValue` are Lettuce core types (`io.lettuce.core` package).

== Item Readers

Each data type has 2 corresponding item readers:

* Snapshot: uses SCAN command to produce keys.
* Live (AKA continuous): uses keyspace notifications to produce keys that have been updated.

== Item Writers

All item writers can perform both inserts or deletes depending on the value and TTL in the incoming object:

* If value is null or TTL is -2 then the `DEL` command is called
* Otherwise a write is performed

=== `KeyDumpItemWriter`

`RestoreOperation` accepts `KeyDump` objects and call the RESTORE command using the byte array and TTL if any.

=== `DataStructureItemWriter`

`DataStructureItemWriter` accepts `DataStructure` objects and calls the write command specific to the data type:

* Hash -> HSET
* List -> LPUSH
* Set -> SADD
* Stream -> XADD
* String -> SET
* Sorted Set -> ZADD

If TTL >= 0 then an additional call is made to `EXPIRE` command.

== Usage

Refer to unit test for usage examples
