name: EarlyAccess

on:
  push:
    branches: [ master ]

jobs:
  earlyaccess:
    name: EarlyAccess
    if: startsWith(github.event.head_commit.message, 'Releasing version') != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: release
        uses: actions/redis-release-action@v1