name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
      branch:
        description: Branch
        default: main
        required: true
      tasks:
        description: Tasks
        default: 'build aggregateTestReports publish'
        required: false
        type: string

jobs:
  release:
    name: Release
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/release.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      tasks: ${{ github.event.inputs.tasks }}
      java-version: 21
    secrets:
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}